---
- name: Install Docker Compose
  ansible.builtin.dnf:
    name: docker-compose
    state: present
    enablerepo: "*linux-x86_64-docker_compose"
  when: docker_compose and ansible_distribution_major_version == '7'

- name: Get Docker subscription
  ansible.builtin.command:
    cmd: subscription-manager list --consumed --matches='Docker' --pool-only
  register: docker_pool
  failed_when: not docker_pool.stdout
  when: not "docker_ce" in version

- name: Remove Docker product
  ansible.builtin.command:
    cmd: subscription-manager remove --pool '{{ docker_pool.stdout }}'
  when: not "docker_ce" in version
