---
- name: Remove old Docker installation
  include_tasks: remove_docker.yml
  when: remove_old and remove_old is defined or only_remove

- name: installation
  block:
    - name: validations
      include_tasks: validations.yml

    - name: Enable needed Subscriptions
      include_tasks: subscriptions.yml
      loop: '{{ pool_name[version] }}'

    - name: Enable needed repositories
      include_tasks: repositories.yml

    - name: Install Docker client from RHEL Repos
      include_tasks: install_docker_rhel.yml
      when: version == 'docker_rhel'

    - name: Install Podman client from RHEL Repos
      include_tasks: install_podman_rhel.yml
      when: version == 'podman_rhel'

    - name: Install Docker client from Community Repos
      include_tasks: install_docker_ce.yml
      when: version == 'docker_ce'

    - name: Install Docker Compose
      include_tasks: install_docker_compose.yml
      when: not "podman_rhel" in version
  when: not only_remove
