---
- name: Validate needed subscriptions
  block:
    - name: Validate if '{{ item }}' subscription are present
      ansible.builtin.command:
        cmd: subscription-manager list --consumed --matches='{{ item }}' --pool-only
      register: pool_id
      failed_when: not pool_id.stdout
      changed_when: pool_id.rc == 1
  rescue:
    - name: Get '{{ item }}' subscription
      ansible.builtin.command:
        cmd: subscription-manager list --available --matches='{{ item }}' --pool-only
      register: pool_id
      failed_when: not pool_id.stdout
      changed_when: pool_id.rc == 1

    - name: Subscribe to '{{ item }}' product
      ansible.builtin.command:
        cmd: subscription-manager attach --pool '{{ pool_id.stdout }}'
      register: attach_pool
      failed_when: not attach_pool.stdout
      changed_when: attach_pool.rc == 1
